const categoryOptions = [
  { value: 'accounting', label: 'Accounting', href: '/categories/accounting' },
  { value: 'advertising', label: 'Advertising', href: '/categories/advertising' },
  { value: 'animals', label: 'Animals', href: '/categories/animals' },
  { value: 'animal-husbandry', label: 'Animal Husbandry', href: '/categories/animal-husbandry' },
  { value: 'animal-breeding', label: 'Animal Breeding', href: '/categories/animal-breeding' },
  { value: 'animal-training', label: 'Animal Training', href: '/categories/animal-training' },
  { value: 'architecture', label: 'Architecture', href: '/categories/architecture' },
  { value: 'audio-production', label: 'Audio Production', href: '/categories/audio-production' },
  { value: 'audio-recording', label: 'Audio Recording', href: '/categories/audio-recording' },
  { value: 'auto-repair', label: 'Auto Repair', href: '/categories/auto-repair' },
  { value: 'automotive', label: 'Automotive', href: '/categories/automotive' },
  { value: 'bookkeeping', label: 'Bookkeeping', href: '/categories/bookkeeping' },
  { value: 'books', label: 'Books', href: '/categories/books' },
  { value: 'business-finance', label: 'Business Finance', href: '/categories/business-finance' },
  { value: 'business-planning', label: 'Business Planning', href: '/categories/business-planning' },
  { value: 'butchers', label: 'Butchers', href: '/categories/butchers' },
  { value: 'carpentry', label: 'Carpentry', href: '/categories/carpentry' },
  { value: 'cigars', label: 'Cigars', href: '/categories/cigars' },
  { value: 'cleaning', label: 'Cleaning', href: '/categories/cleaning' },
  { value: 'clothing', label: 'Clothing', href: '/categories/clothing' },
  { value: 'coffee', label: 'Coffee', href: '/categories/coffee' },
  { value: 'construction', label: 'Construction', href: '/categories/construction' },
  { value: 'design', label: 'Design', href: '/categories/design' },
  { value: 'education', label: 'Education', href: '/categories/education' },
  { value: 'electrical', label: 'Electrical', href: '/categories/electrical' },
  { value: 'engineering', label: 'Engineering', href: '/categories/engineering' },
  { value: 'estate-planning', label: 'Estate Planning', href: '/categories/estate-planning' },
  { value: 'event-planning', label: 'Event Planning', href: '/categories/event-planning' },
  { value: 'farming', label: 'Farming', href: '/categories/farming' },
  { value: 'finance', label: 'Finance', href: '/categories/finance' },
  { value: 'financial-planning', label: 'Financial Planning', href: '/categories/financial-planning' },
  { value: 'firearms', label: 'Firearms', href: '/categories/firearms' },
  { value: 'fitness', label: 'Fitness', href: '/categories/fitness' },
  { value: 'food-and-beverage', label: 'Food and Beverage', href: '/categories/food-and-beverage' },
  { value: 'graphic-design', label: 'Graphic Design', href: '/categories/graphic-design' },
  { value: 'hvac', label: 'HVAC', href: '/categories/hvac' },
  { value: 'home-design', label: 'Home Design', href: '/categories/home-design' },
  { value: 'industrial', label: 'Industrial', href: '/categories/industrial' },
  { value: 'industrial-design', label: 'Industrial Design', href: '/categories/industrial-design' },
  { value: 'insurance', label: 'Insurance', href: '/categories/insurance' },
  { value: 'interior-decorating', label: 'Interior Decorating', href: '/categories/interior-decorating' },
  { value: 'interior-design', label: 'Interior Design', href: '/categories/interior-design' },
  { value: 'investment-advice', label: 'Investment Advice', href: '/categories/investment-advice' },
  { value: 'jewelry', label: 'Jewelry', href: '/categories/jewelry' },
  { value: 'legal', label: 'Legal', href: '/categories/legal' },
  { value: 'legal-services', label: 'Legal Services', href: '/categories/legal-services' },
  { value: 'life-insurance', label: 'Life Insurance', href: '/categories/life-insurance' },
  { value: 'manufacturing', label: 'Manufacturing', href: '/categories/manufacturing' },
  { value: 'marketing', label: 'Marketing', href: '/categories/marketing' },
  { value: 'media-production', label: 'Media Production', href: '/categories/media-production' },
  { value: 'medical', label: 'Medical', href: '/categories/medical' },
  { value: 'medical-billing', label: 'Medical Billing', href: '/categories/medical-billing' },
  { value: 'medical-equipment', label: 'Medical Equipment', href: '/categories/medical-equipment' },
  { value: 'medical-insurance', label: 'Medical Insurance', href: '/categories/medical-insurance' },
  { value: 'medical-coding', label: 'Medical Coding', href: '/categories/medical-coding' },
  { value: 'mortgage', label: 'Mortgage', href: '/categories/mortgage' },
  { value: 'music', label: 'Music', href: '/categories/music' },
  { value: 'music-production', label: 'Music Production', href: '/categories/music-production' },
  { value: 'music-recording', label: 'Music Recording', href: '/categories/music-recording' },
  { value: 'musical-instruments', label: 'Musical Instruments', href: '/categories/musical-instruments' },
  { value: 'news', label: 'News', href: '/categories/news' },
  { value: 'non-profit', label: 'Non-Profit', href: '/categories/non-profit' },
  { value: 'personal-finance', label: 'Personal Finance', href: '/categories/personal-finance' },
  { value: 'pets', label: 'Pets', href: '/categories/pets' },
  { value: 'plumbing', label: 'Plumbing', href: '/categories/plumbing' },
  { value: 'podcasting', label: 'Podcasting', href: '/categories/podcasting' },
  { value: 'private-investigator', label: 'Private Investigator', href: '/categories/private-investigator' },
  { value: 'property-management', label: 'Property Management', href: '/categories/property-management' },
  { value: 'publishing', label: 'Publishing', href: '/categories/publishing' },
  { value: 'real-estate', label: 'Real Estate', href: '/categories/real-estate' },
  { value: 'remodeling', label: 'Remodeling', href: '/categories/remodeling' },
  { value: 'restaurants', label: 'Restaurants', href: '/categories/restaurants' },
  { value: 'retail', label: 'Retail', href: '/categories/retail' },
  { value: 'retirement-planning', label: 'Retirement Planning', href: '/categories/retirement-planning' },
  { value: 'services', label: 'Services', href: '/categories/services' },
  { value: 'software', label: 'Software', href: '/categories/software' },
  { value: 'tax-preparation', label: 'Tax Preparation', href: '/categories/tax-preparation' },
  { value: 'teaching', label: 'Teaching', href: '/categories/teaching' },
  { value: 'tobacco', label: 'Tobacco', href: '/categories/tobacco' },
  { value: 'toys', label: 'Toys', href: '/categories/toys' },
  { value: 'video-production', label: 'Video Production', href: '/categories/video-production' },
  { value: 'video-recording', label: 'Video Recording', href: '/categories/video-recording' },
  { value: 'virtual-assistant', label: 'Virtual Assistant', href: '/categories/virtual-assistant' },
  { value: 'voice-acting', label: 'Voice Acting', href: '/categories/voice-acting' },
  { value: 'wealth-management', label: 'Wealth Management', href: '/categories/wealth-management' },
  { value: 'web-development', label: 'Web Development', href: '/categories/web-development' },
  { value: 'web-applications', label: 'Web Applications', href: '/categories/web-applications' },
  { value: 'web-design', label: 'Web Design', href: '/categories/web-design' },
  { value: 'writing', label: 'Writing', href: '/categories/writing' }
];

export { categoryOptions };