const categoryOptions = [
  { value: 'accounting', label: 'Accounting', href: '/categories/accounting' },
  { value: 'architecture', label: 'Architecture', href: '/categories/architecture' },
  { value: 'audio-production', label: 'Audio Production', href: '/categories/audio-production' },
  { value: 'audio-recording', label: 'Audio Recording', href: '/categories/audio-recording' },
  { value: 'auto-repair', label: 'Auto Repair', href: '/categories/auto-repair' },
  { value: 'automotive', label: 'Automotive', href: '/categories/automotive' },
  { value: 'bookkeeping', label: 'Bookkeeping', href: '/categories/bookkeeping' },
  { value: 'books', label: 'Books', href: '/categories/books' },
  { value: 'business-finance', label: 'Business Finance', href: '/categories/business-finance' },
  { value: 'business-planning', label: 'Business Planning', href: '/categories/business-planning' },
  { value: 'carpentry', label: 'Carpentry', href: '/categories/carpentry' },
  { value: 'clothing', label: 'Clothing', href: '/categories/clothing' },
  { value: 'construction', label: 'Construction', href: '/categories/construction' },
  { value: 'design', label: 'Design', href: '/categories/design' },
  { value: 'education', label: 'Education', href: '/categories/education' },
  { value: 'electrical', label: 'Electrical', href: '/categories/electrical' },
  { value: 'estate-planning', label: 'Estate Planning', href: '/categories/estate-planning' },
  { value: 'finance', label: 'Finance', href: '/categories/finance' },
  { value: 'financial-planning', label: 'Financial Planning', href: '/categories/financial-planning' },
  { value: 'graphic-design', label: 'Graphic Design', href: '/categories/graphic-design' },
  { value: 'hvac', label: 'HVAC', href: '/categories/hvac' },
  { value: 'home-design', label: 'Home Design', href: '/categories/home-design' },
  { value: 'insurance', label: 'Insurance', href: '/categories/insurance' },
  { value: 'interior-decorating', label: 'Interior Decorating', href: '/categories/interior-decorating' },
  { value: 'interior-design', label: 'Interior Design', href: '/categories/interior-design' },
  { value: 'investment-advice', label: 'Investment Advice', href: '/categories/investment-advice' },
  { value: 'jewelry', label: 'Jewelry', href: '/categories/jewelry' },
  { value: 'legal', label: 'Legal', href: '/categories/legal' },
  { value: 'marketing', label: 'Marketing', href: '/categories/marketing' },
  { value: 'non-profit', label: 'Non-Profit', href: '/categories/non-profit' },
  { value: 'personal-finance', label: 'Personal Finance', href: '/categories/personal-finance' },
  { value: 'plumbing', label: 'Plumbing', href: '/categories/plumbing' },
  { value: 'publishing', label: 'Publishing', href: '/categories/publishing' },
  { value: 'real-estate', label: 'Real Estate', href: '/categories/real-estate' },
  { value: 'remodeling', label: 'Remodeling', href: '/categories/remodeling' },
  { value: 'restaurants', label: 'Restaurants', href: '/categories/restaurants' },
  { value: 'retail', label: 'Retail', href: '/categories/retail' },
  { value: 'retirement-planning', label: 'Retirement Planning', href: '/categories/retirement-planning' },
  { value: 'services', label: 'Services', href: '/categories/services' },
  { value: 'software', label: 'Software', href: '/categories/software' },
  { value: 'tax-preparation', label: 'Tax Preparation', href: '/categories/tax-preparation' },
  { value: 'video-production', label: 'Video Production', href: '/categories/video-production' },
  { value: 'video-recording', label: 'Video Recording', href: '/categories/video-recording' },
  { value: 'virtual-assistant', label: 'Virtual Assistant', href: '/categories/virtual-assistant' },
  { value: 'voice-acting', label: 'Voice Acting', href: '/categories/voice-acting' },
  { value: 'wealth-management', label: 'Wealth Management', href: '/categories/wealth-management' },
  { value: 'web-development', label: 'Web Development', href: '/categories/web-development' },
  { value: 'web-applications', label: 'Web Applications', href: '/categories/web-applications' },
  { value: 'web-design', label: 'Web Design', href: '/categories/web-design' },
  { value: 'writing', label: 'Writing', href: '/categories/writing' }
];

export { categoryOptions };