const categoryOptions = [
  { value: 'accounting', label: 'Accounting', href: '/categories/accounting' },
  { value: 'auto-repair', label: 'Auto Repair', href: '/categories/auto-repair' },
  { value: 'automotive', label: 'Automotive', href: '/categories/automotive' },
  { value: 'bookkeeping', label: 'Bookkeeping', href: '/categories/bookkeeping' },
  { value: 'books', label: 'Books', href: '/categories/books' },
  { value: 'clothing', label: 'Clothing', href: '/categories/clothing' },
  { value: 'construction', label: 'Construction', href: '/categories/construction' },
  { value: 'design', label: 'Design', href: '/categories/design' },
  { value: 'education', label: 'Education', href: '/categories/education' },
  { value: 'electrical', label: 'Electrical', href: '/categories/electrical' },
  { value: 'finance', label: 'Finance', href: '/categories/finance' },
  { value: 'financial-planning', label: 'Financial Planning', href: '/categories/financial-planning' },
  { value: 'graphic-design', label: 'Graphic Design', href: '/categories/graphic-design' },
  { value: 'hvac', label: 'HVAC', href: '/categories/hvac' },
  { value: 'insurance', label: 'Insurance', href: '/categories/insurance' },
  { value: 'jewelry', label: 'Jewelry', href: '/categories/jewelry' },
  { value: 'legal', label: 'Legal', href: '/categories/legal' },
  { value: 'marketing', label: 'Marketing', href: '/categories/marketing' },
  { value: 'plumbing', label: 'Plumbing', href: '/categories/plumbing' },
  { value: 'publishing', label: 'Publishing', href: '/categories/publishing' },
  { value: 'real-estate', label: 'Real Estate', href: '/categories/real-estate' },
  { value: 'remodeling', label: 'Remodeling', href: '/categories/remodeling' },
  { value: 'restaurants', label: 'Restaurants', href: '/categories/restaurants' },
  { value: 'retail', label: 'Retail', href: '/categories/retail' },
  { value: 'services', label: 'Services', href: '/categories/services' },
  { value: 'software', label: 'Software', href: '/categories/software' },
  { value: 'tax-preparation', label: 'Tax Preparation', href: '/categories/tax-preparation' },
  { value: 'virtual-assistant', label: 'Virtual Assistant', href: '/categories/virtual-assistant' },
  { value: 'web-development', label: 'Web Development', href: '/categories/web-development' },
  { value: 'writing', label: 'Writing', href: '/categories/writing' },
  { value: 'other', label: 'Other', href: '/categories/other' }
];

export { categoryOptions };